# @package _global_
# Dataset configuration
dataset_file: "coco"
tr_npy_path: "data/npy/CT_Abd"
coco_path: "data/processed/coco_1024_2014"
train_annotation_file: "train.json"
val_annotation_file: "test.json"
train_image_folder: "../../intermediate/patches_1024_1024/images/train"
val_image_folder: "../../intermediate/patches_1024_1024/images/test"
remove_difficult: false

# Image processing configuration
img_size: 1024

# Number of classes (excluding background)
num_classes: 6