defaults:
  - model: vit_l
  - training: default
  - dataset: default
  - _self_

# Main configuration
task_name: "MedSAM-${name}"
work_dir: "./exp/box_model"
output_dir: ""
device: "cuda"
seed: 42
use_wandb: false
use_amp: false
resume: ""
distributed: false

# Image processing configuration (shared across all models)
img_size: 1024

# Loss configuration (from train_config.yaml)
loss:
  focal_loss_weight: 0.0
  focal_loss_gamma: 2.0
  bbox_loss_weight: 1.0
  mask_loss_weight: 1.0

# Scheduler configuration (from train_config.yaml)
# scheduler:
#  type: "cosine"
#  warmup_epochs: 5
#  min_lr: 1e-6