# Aggressive data augmentation configuration
# Strong augmentations for robust training with limited data

augmentation:
  pipeline_type: "aggressive"

  # Image processing
  image_size: [1024, 1024]

  # Augmentation probabilities (high)
  strong_aug_prob: 0.8
  geometric_aug_prob: 0.8
  photometric_aug_prob: 0.7
  weather_aug_prob: 0.4
  aerial_specific_prob: 0.5

  # Geometric augmentations
  geometric:
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.4
    rotate90_prob: 0.6
    rotation_limit: 20
    affine_prob: 0.6
    affine_params:
      scale: [0.7, 1.3]
      translate_percent: [-0.15, 0.15]
      rotate: [-20, 20]
      shear: [-8, 8]
    perspective_prob: 0.4
    perspective_scale: [0.05, 0.12]

  # Photometric augmentations
  photometric:
    brightness_contrast_prob: 0.7
    brightness_limit: 0.25
    contrast_limit: 0.25
    hue_saturation_prob: 0.6
    hue_shift_limit: 15
    sat_shift_limit: 20
    val_shift_limit: 15
    color_jitter_prob: 0.6
    color_jitter_params:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1

  # Noise and blur
  noise_blur:
    gaussian_noise_prob: 0.4
    noise_var_limit: [10.0, 60.0]
    motion_blur_prob: 0.3
    gaussian_blur_prob: 0.3
    median_blur_prob: 0.2
    blur_limit: 5

  # Weather effects
  weather:
    rain_prob: 0.25
    rain_params:
      slant_range: [-12, 12]
      drop_length: 1
      drop_width: 1
      brightness_coefficient: 0.8
    fog_prob: 0.2
    fog_params:
      fog_coef_range: [0.1, 0.35]
      alpha_coef: 0.1
    sun_flare_prob: 0.15
    sun_flare_params:
      flare_roi: [0, 0, 1, 0.5]
      num_flare_circles: [1, 3]

  # Aerial specific
  aerial_specific:
    coarse_dropout_prob: 0.4
    coarse_dropout_params:
      max_holes: 10
      max_hole_size: 32
      min_holes: 2
      min_hole_size: 8
    grid_dropout_prob: 0.2
    grid_dropout_params:
      ratio: 0.5
      unit_size_range: [2, 16]

  # Advanced effects
  advanced_effects:
    clahe_prob: 0.3
    emboss_prob: 0.2
    sharpen_prob: 0.3

  # Copy-paste augmentation
  copy_paste:
    enabled: true
    paste_prob: 0.4
    max_paste_objects: 5
    scale_range: [0.5, 1.6]
    overlap_threshold: 0.25

  # Mosaic and mixup
  advanced:
    mosaic_prob: 0.5
    mixup_prob: 0.2
    mixup_alpha: 0.3

  # Sampling strategy for class imbalance
  sampling:
    strategy: "minority_oversampling"  # Options: random, weighted, class_aware, minority_oversampling
    batch_size: 8
    minority_boost_factor: 3.0
    min_class_samples: 2
    shuffle: true

# Normalization (ImageNet values)
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Special settings for small datasets
small_dataset:
  enabled: true

  # Oversampling settings
  oversample_minority: true
  oversample_factor: 2.0

  # Pseudo-labeling with SAM
  pseudo_labeling:
    enabled: false  # Can be enabled when SAM integration is available
    confidence_threshold: 0.7
    max_pseudo_samples: 1000