# Standard data augmentation configuration
# Balanced augmentations for general training

augmentation:
  pipeline_type: "standard"

  # Image processing
  image_size: [1024, 1024]

  # Augmentation probabilities (moderate)
  strong_aug_prob: 0.6
  geometric_aug_prob: 0.7
  photometric_aug_prob: 0.6
  weather_aug_prob: 0.2
  aerial_specific_prob: 0.3

  # Geometric augmentations
  geometric:
    horizontal_flip_prob: 0.5
    vertical_flip_prob: 0.3
    rotate90_prob: 0.5
    rotation_limit: 15
    affine_prob: 0.4
    affine_params:
      scale: [0.8, 1.2]
      translate_percent: [-0.1, 0.1]
      rotate: [-15, 15]
      shear: [-5, 5]
    perspective_prob: 0.2
    perspective_scale: [0.05, 0.08]

  # Photometric augmentations
  photometric:
    brightness_contrast_prob: 0.6
    brightness_limit: 0.2
    contrast_limit: 0.2
    hue_saturation_prob: 0.5
    hue_shift_limit: 10
    sat_shift_limit: 15
    val_shift_limit: 12
    color_jitter_prob: 0.4
    color_jitter_params:
      brightness: 0.15
      contrast: 0.15
      saturation: 0.15
      hue: 0.08

  # Noise and blur
  noise_blur:
    gaussian_noise_prob: 0.3
    noise_var_limit: [10.0, 40.0]
    motion_blur_prob: 0.2
    gaussian_blur_prob: 0.2
    median_blur_prob: 0.1
    blur_limit: 4

  # Weather effects
  weather:
    rain_prob: 0.15
    rain_params:
      slant_range: [-8, 8]
      drop_length: 1
      drop_width: 1
      brightness_coefficient: 0.9
    fog_prob: 0.1
    fog_params:
      fog_coef_range: [0.1, 0.25]
      alpha_coef: 0.08
    sun_flare_prob: 0.08
    sun_flare_params:
      flare_roi: [0, 0, 1, 0.4]
      num_flare_circles: [1, 2]

  # Aerial specific
  aerial_specific:
    coarse_dropout_prob: 0.2
    coarse_dropout_params:
      max_holes: 6
      max_hole_size: 24
      min_holes: 1
      min_hole_size: 8
    grid_dropout_prob: 0.1
    grid_dropout_params:
      ratio: 0.4
      unit_size_range: [2, 12]

  # Advanced effects
  advanced_effects:
    clahe_prob: 0.2
    emboss_prob: 0.1
    sharpen_prob: 0.2

  # Copy-paste augmentation
  copy_paste:
    enabled: true
    paste_prob: 0.2
    max_paste_objects: 3
    scale_range: [0.6, 1.4]
    overlap_threshold: 0.3

  # Mosaic and mixup
  advanced:
    mosaic_prob: 0.3
    mixup_prob: 0.1
    mixup_alpha: 0.2

  # Sampling strategy
  sampling:
    strategy: "class_aware"  # Options: random, weighted, class_aware, minority_oversampling
    batch_size: 8
    samples_per_class: 2
    shuffle: true

# Normalization (ImageNet values)
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]